from hackathon.models import Merchant, MerchantRating, Area, Neighbourhood, User, Service  # Import the model classes we just wrote.
# No questions are in the system yet.
Merchant.objects.all()
# Create a new Question.
# Support for time zones is enabled in the default settings file, so
# Django expects a datetime with tzinfo for pub_date. Use timezone.now()
# instead of datetime.datetime.now() and it will do the right thing.
from django.utils import timezone
a1 = Area(name="Pretoria")
a2 = Area(name="Johannesburg")
a3 = Area(name="Johannesburg")
a4 = Area(name="Pretoria")
a5 = Area(name="Centurion")
a6 = Area(name="Soweto")
a7 = Area(name="Boksburg")
a8 = Area(name="Tembisa")
a9 = Area(name="Pretoria")
a10 = Area(name="Ga-Rankuwa")
a11 = Area(name="Shoshanguve")
a12 = Area(name="Mabopane")
a13 = Area(name="Brakpan")
a14 = Area(name="Springs")
a15 = Area(name="Soweto")
a16 = Area(name="Soweto")
a17 = Area(name="Boksburg")
a18 = Area(name="Pretoria")
a19 = Area(name="Vosloorus")
a20 = Area(name="Johannesburg")

a1.save()
a2.save()
a3.save()
a4.save()
a5.save()
a6.save()
a7.save()
a8.save()
a9.save()
a10.save()
a11.save()
a12.save()
a13.save()
a14.save()
a15.save()
a16.save()
a17.save()
a18.save()
a19.save()
a20.save()

n1 = Neighbourhood(area=a1, name="Brooklyn")
n2 = Neighbourhood(area=a2, name="Northcliff")
n3 = Neighbourhood(area=a3, name="Linden")
n4 = Neighbourhood(area=a4, name="Menlyn")
n5 = Neighbourhood(area=a5, name="Monavoni")
n6 = Neighbourhood(area=a6, name="Zola")
n7 = Neighbourhood(area=a7, name="Sunward Park")
n8 = Neighbourhood(area=a8, name="Tembisa")
n9 = Neighbourhood(area=a9, name="Mamelodi")
n10 = Neighbourhood(area=a10, name="Zone 2")
n11 = Neighbourhood(area=a11, name="Block L")
n12 = Neighbourhood(area=a12, name="Unit C")
n13 = Neighbourhood(area=a13, name="Tskane")
n14 = Neighbourhood(area=a14, name="Kwa-Thema")
n15 = Neighbourhood(area=a15, name="Diepkloof")
n16 = Neighbourhood(area=a16, name="Pimville")
n17 = Neighbourhood(area=a17, name="Dawn Park")
n18 = Neighbourhood(area=a18, name="Lynwood")
n19 = Neighbourhood(area=a19, name="Ext 2")
n20 = Neighbourhood(area=a20, name="Rosebank")

# Save the object into the database. You have to call save() explicitly.
n1.save()
n2.save()
n3.save()
n4.save()
n5.save()
n6.save()
n7.save()
n8.save()
n9.save()
n10.save()
n11.save()
n12.save()
n13.save()
n14.save()
n15.save()
n16.save()
n17.save()
n18.save()
n19.save()
n20.save()


s1 = Service(name="Plumbing")
s1.save()
s2 = Service(name="Appliance Repairs")
s2.save()
s = Service(name="Brick Layer")
s.save()
s = Service(name="Carpenters")
s.save()
s = Service(name="Cleaners - Domestic")
s.save()
s = Service(name="Cleaners - Carpet/ Sofas")
s.save()
s = Service(name="Ceilings")
s.save()
s = Service(name="Chimney Repairs")
s.save()
s = Service(name="Doors")
s.save()
s3 = Service(name="Electrician")
s3.save()
s = Service(name="Furniture Custom Made & Repairs")
s.save()
s = Service(name="Garage Doors")
s.save()
s4 = Service(name="Gardening Service")
s4.save()
s = Service(name="Gates")
s.save()
s = Service(name="Gutter Cleaning")
s.save()
s = Service(name="HandyMan")
s.save()
s = Service(name="Heating and Air Conditioning & Ventilation")
s.save()
s5 = Service(name="Domestic")
s5.save()
s6 = Service(name="Nanny")
s6.save()
s = Service(name="Welder")
s.save()

m1 = Merchant(username="Tembi", email="tembi@tembi.com", place=n1, talent=s2)
m2 = Merchant(username="Thabo", email="thabo@tembi.com", place=n2, talent=s1)  
m3 = Merchant(username="Teboho", email="tebs@tembi.com", place=n3, talent=s5)  
m4 = Merchant(username="Tumi", email="tumi@tembi.com", place=n4, talent=s6)  
m5 = Merchant(username="Vima", email="vima@tembi.com", place=n5, talent=s1)  
m6 = Merchant(username="Deli", email="deli@tembi.com", place=n6, talent=s3) 
m7 = Merchant(username="Veli", email="veli@tembi.com", place=n7, talent=s2) 
m8 = Merchant(username="Lindi", email="lindi@tembi.com", place=n8, talent=s3) 
m9 = Merchant(username="Zozo", email="zozo@tembi.com", place=n9, talent=s4) 
m10 = Merchant(username="Gogo", email="gogo@tembi.com", place=n10, talent=s1) 
m11 = Merchant(username="Gigi", email="gigi@tembi.com", place=n11, talent=s1) 
m12 = Merchant(username="Gugu", email="gugu@tembi.com", place=n12, talent=s5) 
m13 = Merchant(username="nana", email="nana@tembi.com", place=n13, talent=s2) 
m14 = Merchant(username="lala", email="lala@tembi.com", place=n14, talent=s5) 
m15 = Merchant(username="baba", email="baba@tembi.com", place=n15, talent=s4) 
m16 = Merchant(username="sisi", email="sisi@tembi.com", place=n16, talent=s2) 
m17 = Merchant(username="wendy", email="wendy@tembi.com", place=n17, talent=s6) 
m18 = Merchant(username="thoko", email="thoko@tembi.com", place=n18, talent=s6) 
m19 = Merchant(username="thandi", email="thandeka@tembi.com", place=n19, talent=s4) 
m20 = Merchant(username="beki", email="beki@tembi.com", place=n20, talent=s4)

m1.save()
m2.save()
m3.save() 
m4.save() 
m5.save()
m6.save()
m7.save()
m8.save()
m9.save()
m10.save()
m11.save()
m12.save()
m13.save()
m14.save()
m15.save()
m16.save()
m17.save()
m18.save()
m19.save()
m20.save()


u1 = User(username = "lali", email="lali@lali.com")
u2 = User(username = "lindi", email="lindi@lali.com")
u3 = User(username = "poppy", email="lali@lali.com")
u4 = User(username = "tutu", email="tutu@lali.com")
u5 = User(username = "voma", email="vuvu@lali.com")
u6 = User(username = "zama", email="zama@lali.com")
u7 = User(username = "rama", email="rama@lali.com")
u8 = User(username = "coma", email="coma@lali.com")
u9 = User(username = "soma", email="soma@lali.com")
u10 = User(username = "pepa", email="pepa@lali.com")
u11 = User(username = "zizi", email="zizi@lali.com")
u12 = User(username = "sipho", email="sipho@lali.com")
u12 = User(username = "naledi", email="naledi@lali.com")
u13 = User(username = "precious", email="precious@lali.com")
u14 = User(username = "pretty", email="pretty@lali.com")
u15 = User(username = "sophy", email="sofy@lali.com")
u16 = User(username = "aggy", email="agnes@lali.com")
u17 = User(username = "patience", email="patience@lali.com")
u18 = User(username = "happy", email="happi@lali.com")
u19 = User(username = "futhi", email="futhi@lali.com")
u20 = User(username = "lindo", email="lindo@lali.com")

u1.save()
u2.save()
u3.save()
u4.save()
u5.save()
u6.save()
u7.save()
u8.save()
u9.save()
u10.save()
u11.save()
u12.save()
u13.save()
u14.save()
u15.save()
u16.save()
u17.save()
u18.save()
u19.save()
u20.save()

r1 = MerchantRating(merchant=m1, user=u1)
r2 = MerchantRating(merchant=m2, user=u2)
r3 = MerchantRating(merchant=m3, user=u3)
r4 = MerchantRating(merchant=m4, user=u4)
r5 = MerchantRating(merchant=m5, user=u5)
r6 = MerchantRating(merchant=m6, user=u6)
r7 = MerchantRating(merchant=m7, user=u7)
r8 = MerchantRating(merchant=m8, user=u8)
r9 = MerchantRating(merchant=m9, user=u9)
r10 = MerchantRating(merchant=m10, user=u10)
r11 = MerchantRating(merchant=m11, user=u11)
r12 = MerchantRating(merchant=m12, user=u12)
r13 = MerchantRating(merchant=m13, user=u13)
r14 = MerchantRating(merchant=m14, user=u14)
r15 = MerchantRating(merchant=m15, user=u15)
r16 = MerchantRating(merchant=m16, user=u16)
r17 = MerchantRating(merchant=m17, user=u17)
r18 = MerchantRating(merchant=m18, user=u18)
r19 = MerchantRating(merchant=m19, user=u19)
r20 = MerchantRating(merchant=m20, user=u20)

r1.save()
r2.save()
r3.save()
r4.save()
r5.save()
r6.save()
r7.save()
r8.save()
r9.save()
r10.save()
r11.save()
r12.save()
r13.save()
r14.save()
r15.save()
r16.save()
r17.save()
r18.save()
r19.save()
r20.save()

